// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
//import 'dart:js';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTj9fewawSRPE_NfwNiNzrPAlbSYQPerA',
    appId: '1:499006048690:web:711b398c0aa88bfc0b7cab',
    messagingSenderId: '499006048690',
    projectId: 'etmsprojectlogin',
    authDomain: 'etmsprojectlogin.firebaseapp.com',
    storageBucket: 'etmsprojectlogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyCirxCHoX6mbtYyI1Q0VSKWNYICfasPw',
    appId: '1:499006048690:android:57318c04c1f0837a0b7cab',
    messagingSenderId: '499006048690',
    projectId: 'etmsprojectlogin',
    storageBucket: 'etmsprojectlogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJMir1pZgHHW1BGHWyK_gj0dTr8B1ci0M',
    appId: '1:499006048690:ios:61c54d969185cc9f0b7cab',
    messagingSenderId: '499006048690',
    projectId: 'etmsprojectlogin',
    storageBucket: 'etmsprojectlogin.appspot.com',
    androidClientId:
        '499006048690-r44e5s4avtu2d40fpsjo6k3ssfdhoo18.apps.googleusercontent.com',
    iosClientId:
        '499006048690-hbcjb2utv0fn6n36dbndkjjvgho96glb.apps.googleusercontent.com',
    iosBundleId: 'com.example.etmsAttachmentProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJMir1pZgHHW1BGHWyK_gj0dTr8B1ci0M',
    appId: '1:499006048690:ios:61c54d969185cc9f0b7cab',
    messagingSenderId: '499006048690',
    projectId: 'etmsprojectlogin',
    storageBucket: 'etmsprojectlogin.appspot.com',
    androidClientId:
        '499006048690-r44e5s4avtu2d40fpsjo6k3ssfdhoo18.apps.googleusercontent.com',
    iosClientId:
        '499006048690-hbcjb2utv0fn6n36dbndkjjvgho96glb.apps.googleusercontent.com',
    iosBundleId: 'com.example.etmsAttachmentProject',
  );
}
